language: python
python: '3.5'
sudo: false
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
  matrix:
    - TOXENV=check
    #- TOXENV=docs

    - TOXENV=2.7-cover,coveralls
    - TOXENV=2.7-nocov
    - TOXENV=3.3-cover,coveralls
    - TOXENV=3.3-nocov
    - TOXENV=3.4-cover,coveralls
    - TOXENV=3.4-nocov
    - TOXENV=3.5-cover,coveralls
    - TOXENV=3.5-nocov
    - TOXENV=pypy-cover,coveralls
    - TOXENV=pypy-nocov
before_install:
  - python --version
  - uname -a
  - lsb_release -a
  - sudo mkdir -p /downloads
  - sudo chmod a+rw /downloads
  - curl -L http://sourceforge.net/projects/pyqt/files/sip/sip-4.16.5/sip-4.16.5.tar.gz -o /downloads/sip.tar.gz 
  - curl -L http://sourceforge.net/projects/pyqt/files/PyQt4/PyQt-4.11.3/PyQt-x11-gpl-4.11.3.tar.gz -o /downloads/pyqt4.tar.gz
    # Builds
  - sudo mkdir -p /builds
  - sudo chmod a+rw /builds
install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get install -y libqt4-dev
  - sudo apt-get install -y mesa-common-dev libgl1-mesa-dev libglu1-mesa-dev
# - sudo apt-get install -y python3-sip python3-sip-dev python3-pyqt4 cmake
  # Qt4
  - pushd /builds
  # SIP
  - tar xzf /downloads/sip.tar.gz --keep-newer-files
  - pushd sip-4.16.5
  - python configure.py
  - make
  - sudo make install
  - popd
  # PyQt4
  - tar xzf /downloads/pyqt4.tar.gz --keep-newer-files
  - pushd PyQt-x11-gpl-4.11.3
  - python configure.py -c --confirm-license --no-designer-plugin -e QtCore -e QtGui -e QtTest
  - make
  - sudo make install
  - popd
    # Builds Complete
  - popd

  - pip install tox
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version
script:
  - tox -v
after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat
before_cache:
  - rm -rf $HOME/.cache/pip/log
cache:
  directories:
    - $HOME/.cache/pip
notifications:
  email:
    on_success: never
    on_failure: always
